
/** Generated by generate-component-routes.ts */
import { UIAccordionExample } from '../../../../../projects/ui/src/lib/accordion/example';
import { UIAvatarExample } from '../../../../../projects/ui/src/lib/avatar/example';
import { UIBadgeExample } from '../../../../../projects/ui/src/lib/badge/example';
import { UIButtonExample } from '../../../../../projects/ui/src/lib/button/example';
import { UICardExample } from '../../../../../projects/ui/src/lib/card/example';
import { UIChipExample } from '../../../../../projects/ui/src/lib/chip/example';
import { UIChipGroupExample } from '../../../../../projects/ui/src/lib/chip-group/example';
import { UIDialogExample } from '../../../../../projects/ui/src/lib/dialog/example';
import { UIIconExample } from '../../../../../projects/ui/src/lib/icon/example';
import { UIInputExample } from '../../../../../projects/ui/src/lib/input/example';
import { UIListItemExample } from '../../../../../projects/ui/src/lib/list-item/example';
import { UIModalExample } from '../../../../../projects/ui/src/lib/modal/example';
import { UIPaginationExample } from '../../../../../projects/ui/src/lib/pagination/example';
import { UIRadioExample } from '../../../../../projects/ui/src/lib/radio/example';
import { UIScrimExample } from '../../../../../projects/ui/src/lib/scrim/example';
import { UITableExample } from '../../../../../projects/ui/src/lib/table/example';
import { UITagExample } from '../../../../../projects/ui/src/lib/tag/example';
import { UITooltipExample } from '../../../../../projects/ui/src/lib/tooltip/example';
import { UITruncatedExample } from '../../../../../projects/ui/src/lib/truncated/example';
import { UITxtExample } from '../../../../../projects/ui/src/lib/txt/example';
import { NavRoute } from '../types';

export const componentItems: NavRoute[] = [
    { title: 'Components', section: true },
    { path: 'accordion', component: UIAccordionExample, title: 'Accordion' },
    { path: 'avatar', component: UIAvatarExample, title: 'Avatar' },
    { path: 'badge', component: UIBadgeExample, title: 'Badge' },
    { path: 'button', component: UIButtonExample, title: 'Button' },
    { path: 'card', component: UICardExample, title: 'Card' },
    { path: 'chip', component: UIChipExample, title: 'Chip' },
    { path: 'chip-group', component: UIChipGroupExample, title: 'ChipGroup' },
    { path: 'dialog', component: UIDialogExample, title: 'Dialog' },
    { path: 'icon', component: UIIconExample, title: 'Icon' },
    { path: 'input', component: UIInputExample, title: 'Input' },
    { path: 'list-item', component: UIListItemExample, title: 'ListItem' },
    { path: 'modal', component: UIModalExample, title: 'Modal' },
    { path: 'pagination', component: UIPaginationExample, title: 'Pagination' },
    { path: 'radio', component: UIRadioExample, title: 'Radio' },
    { path: 'scrim', component: UIScrimExample, title: 'Scrim' },
    { path: 'table', component: UITableExample, title: 'Table' },
    { path: 'tag', component: UITagExample, title: 'Tag' },
    { path: 'tooltip', component: UITooltipExample, title: 'Tooltip' },
    { path: 'truncated', component: UITruncatedExample, title: 'Truncated' },
    { path: 'txt', component: UITxtExample, title: 'Txt' },
];
