
/** Generated by generate-component-routes.ts */
import { NavRoute } from '../types';

export const componentItems: NavRoute[] = [
    { title: 'Components', section: true },
    {
        path: 'accordion',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/accordion/example').then((m) => m.UIAccordionExample),
        title: 'Accordion',
    },
    {
        path: 'avatar',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/avatar/example').then((m) => m.UIAvatarExample),
        title: 'Avatar',
    },
    {
        path: 'avatar-group',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/avatar-group/example').then((m) => m.UIAvatarGroupExample),
        title: 'AvatarGroup',
    },
    {
        path: 'badge',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/badge/example').then((m) => m.UIBadgeExample),
        title: 'Badge',
    },
    {
        path: 'banner-alert',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/banner-alert/example').then((m) => m.UIBannerAlertExample),
        title: 'BannerAlert',
    },
    {
        path: 'breadcrumb',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/breadcrumb/example').then((m) => m.UIBreadcrumbExample),
        title: 'Breadcrumb',
    },
    {
        path: 'button',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/button/example').then((m) => m.UIButtonExample),
        title: 'Button',
    },
    {
        path: 'card',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/card/example').then((m) => m.UICardExample),
        title: 'Card',
    },
    {
        path: 'checkbox',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/checkbox/example').then((m) => m.UICheckboxExample),
        title: 'Checkbox',
    },
    {
        path: 'checkbox-group',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/checkbox-group/example').then((m) => m.UICheckboxGroupExample),
        title: 'CheckboxGroup',
    },
    {
        path: 'checkbox-option',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/checkbox-option/example').then((m) => m.UICheckboxOptionExample),
        title: 'CheckboxOption',
    },
    {
        path: 'chip',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/chip/example').then((m) => m.UIChipExample),
        title: 'Chip',
    },
    {
        path: 'chip-group',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/chip-group/example').then((m) => m.UIChipGroupExample),
        title: 'ChipGroup',
    },
    {
        path: 'dialog',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/dialog/example').then((m) => m.UIDialogExample),
        title: 'Dialog',
    },
    {
        path: 'divider',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/divider/example').then((m) => m.UIDividerExample),
        title: 'Divider',
    },
    {
        path: 'field',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/field/example').then((m) => m.UIFieldExample),
        title: 'Field',
    },
    {
        path: 'floating',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/floating/example').then((m) => m.UIFloatingExample),
        title: 'Floating',
    },
    {
        path: 'focus-trap',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/focus-trap/example').then((m) => m.UIFocusTrapExample),
        title: 'FocusTrap',
    },
    {
        path: 'icon',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/icon/example').then((m) => m.UIIconExample),
        title: 'Icon',
    },
    {
        path: 'inline-alert',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/inline-alert/example').then((m) => m.UIInlineAlertExample),
        title: 'InlineAlert',
    },
    {
        path: 'input',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/input/example').then((m) => m.UIInputExample),
        title: 'Input',
    },
    {
        path: 'input-field',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/input-field/example').then((m) => m.UIInputFieldExample),
        title: 'InputField',
    },
    {
        path: 'input-number',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/input-number/example').then((m) => m.UIInputNumberExample),
        title: 'InputNumber',
    },
    {
        path: 'key-navigation',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/key-navigation/example').then((m) => m.UIKeyNavigationExample),
        title: 'KeyNavigation',
    },
    {
        path: 'link',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/link/example').then((m) => m.UILinkExample),
        title: 'Link',
    },
    {
        path: 'list-item',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/list-item/example').then((m) => m.UIListItemExample),
        title: 'ListItem',
    },
    {
        path: 'menu',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/menu/example').then((m) => m.UIMenuExample),
        title: 'Menu',
    },
    {
        path: 'modal',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/modal/example').then((m) => m.UIModalExample),
        title: 'Modal',
    },
    {
        path: 'outside-click',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/outside-click/example').then((m) => m.UIOutsideClickExample),
        title: 'OutsideClick',
    },
    {
        path: 'pagination',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/pagination/example').then((m) => m.UIPaginationExample),
        title: 'Pagination',
    },
    {
        path: 'radio',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/radio/example').then((m) => m.UIRadioExample),
        title: 'Radio',
    },
    {
        path: 'radio-group',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/radio-group/example').then((m) => m.UIRadioGroupExample),
        title: 'RadioGroup',
    },
    {
        path: 'radio-option',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/radio-option/example').then((m) => m.UIRadioOptionExample),
        title: 'RadioOption',
    },
    {
        path: 'scrim',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/scrim/example').then((m) => m.UIScrimExample),
        title: 'Scrim',
    },
    {
        path: 'segmented-control',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/segmented-control/example').then((m) => m.UISegmentedControlExample),
        title: 'SegmentedControl',
    },
    {
        path: 'select',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/select/example').then((m) => m.UISelectExample),
        title: 'Select',
    },
    {
        path: 'switch',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/switch/example').then((m) => m.UISwitchExample),
        title: 'Switch',
    },
    {
        path: 'switch-option',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/switch-option/example').then((m) => m.UISwitchOptionExample),
        title: 'SwitchOption',
    },
    {
        path: 'tab-group',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/tab-group/example').then((m) => m.UITabGroupExample),
        title: 'TabGroup',
    },
    {
        path: 'tab-list',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/tab-list/example').then((m) => m.UITabListExample),
        title: 'TabList',
    },
    {
        path: 'table',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/table/example').then((m) => m.UITableExample),
        title: 'Table',
    },
    {
        path: 'tag',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/tag/example').then((m) => m.UITagExample),
        title: 'Tag',
    },
    {
        path: 'textarea',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/textarea/example').then((m) => m.UITextareaExample),
        title: 'Textarea',
    },
    {
        path: 'textarea-field',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/textarea-field/example').then((m) => m.UITextareaFieldExample),
        title: 'TextareaField',
    },
    {
        path: 'tooltip',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/tooltip/example').then((m) => m.UITooltipExample),
        title: 'Tooltip',
    },
    {
        path: 'txt',
        loadComponent: () =>
            import('../../../../../projects/ui/src/lib/txt/example').then((m) => m.UITxtExample),
        title: 'Txt',
    },
];
