/**
 * Create a example file for a component dynamically based on the component's metadata. This is intended to be run after
 * the metadata file has been generated by the meta script.
 *
 * $ npx tsx .scripts/generate-example.ts <component-slug>
 */

import fs from 'fs';
import { execSync } from 'child_process';
import { generateMeta } from './generate-meta';

const COMPONENT_SLUG = process.argv[2];

if (!COMPONENT_SLUG) {
    console.error('Please provide a component slug as an argument.');
    process.exit(1);
}

const meta = generateMeta();

const metadata = meta.components.find((comp) => comp.slug === COMPONENT_SLUG);

if (!metadata) {
    console.error(`No metadata found for component slug "${COMPONENT_SLUG}".`);
    process.exit(1);
}

console.log(`Generating example file for component "${metadata.name}"...`);

try {
    const exampleFilePath = `projects/demo/src/app/examples/${metadata.slug}/${metadata.slug}-example.component.ts`;

    if (fs.existsSync(exampleFilePath)) {
        console.error(
            `Example file already exists at "${exampleFilePath}". Use a different slug or delete the existing file.`,
        );
        process.exit(1);
    }

    const exampleContent = generateExampleContent(metadata);
    fs.writeFileSync(exampleFilePath, exampleContent);
    console.log(`Example file created at "${exampleFilePath}".`);
} catch (error) {
    console.error('Error generating example file:', error);
    process.exit(1);
}

function generateExampleContent(metadata: any): string {
    let template = '';

    // generate a default example with all inputs set to their default values

    template += `
    <!-- Default example template for ' + metadata.name + ' -->
    <h4>Default</h4>
    <ui-${metadata.slug}  />
    
    `;

    // generate examples for each optional input, with the input set to a non-default value

    // if a particular input has several possible values (like an enum), generate an example for each possible value

    return `import { Component } from '@angular/core';

@Component({
    selector: 'app-${metadata.slug}-example',
    template: \`
    // generated example template for ${metadata.name}
        <p>${metadata.name} example works!</p>
    \`,
    styles: \`
        /* Add example-specific styles here */
    \`
})
export class ${metadata.name}ExampleComponent {
    // Add example-specific logic here
}
`;
}
