/**
 * Generates example components for each Example component (example.ts) in the UI library ("projects/ui/src/lib/*") and
 * creates a route file at "projects/demo/src/app/routes/generated.ts".
 *
 * $ npx tsx .scripts/pre-build.ts
 */

// get a list of all example files

import { pretty, toPascalCase } from './utils';
import fs from 'fs';
import path from 'path';

const __dirname = path.dirname(new URL(import.meta.url).pathname);

const uiLibPath = path.join(__dirname, '../projects/ui/src/lib');
const examples = fs
    .readdirSync(uiLibPath, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory() && fs.existsSync(path.join(uiLibPath, dirent.name, 'example.ts')))
    .map((dirent) => ({ name: toPascalCase(dirent.name), slug: dirent.name }));

const generatedRoutesPath = 'projects/demo/src/app/routes/generated.ts';

fs.writeFileSync(
    path.join(__dirname, '..', generatedRoutesPath),
    `/** Generated by generate-component-routes.ts */
${examples
    .map(({ slug, name }) => `import { UI${name}Example } from '../../../../../projects/ui/src/lib/${slug}/example';`)
    .join('\n')}
import { NavRoute } from '../types';

export const componentItems: NavRoute[] = [
    { title: 'Components', section: true },
     ${examples.map(({ slug, name }) => `{ path: '${slug}', component: UI${name}Example, title: '${name}' },`).join('\n')}
];
`,
);

pretty(path.join(__dirname, '..', generatedRoutesPath));

console.log(`\n\x1b[32m✅ Generated component routes at projects/demo/src/app/routes/generated.ts 📄\x1b[0m\n`);
