/** Generates new projects/ui/src/public-api.ts with all exports from lib folder */
import * as fs from 'fs';
import * as path from 'path';

export function getPublicApiFileContent() {
    const __dirname = path.dirname(new URL(import.meta.url).pathname);

    const libDir = path.join(__dirname, '../projects/ui/src/lib');
    const publicApiPath = path.join(__dirname, '../projects/ui/src/public-api.ts');

    const files = fs
        .readdirSync(libDir, { withFileTypes: true })
        .flatMap((dirent) => (dirent.isDirectory() ? [dirent.name] : []));

    const exportLines = files.map((file) => `export * from './lib/${file}';`);

    const publicApiContent = `/**
 * Public API Surface of UI library
 *
 * Generated by .scripts/update-public-api.ts
 */

${exportLines.join('\n')}
`;

    return { publicApiPath, publicApiContent };
}

// if --write flag is provided, write the file
if (process.argv.includes('--write')) {
    const { publicApiPath, publicApiContent } = getPublicApiFileContent();
    fs.writeFileSync(publicApiPath, publicApiContent);
    console.log('Updated public API at', publicApiPath);
}
